In [1]:
import pandas as pd
import numpy as np
from pandas import DataFrame, Series

In [2]:
# load csv file into dataframe
top_actors_rating = pd.read_csv('top_actors_rating.csv')

# show dataframe
top_actors_rating

,actor_name,genre,movie_rating,movie_title,release_date,production_company
0,Ryan Gosling,drama,9.0,Urban Hunt,7/3/2017,Google
1,Ryan Gosling,sci-fi,8.9,Veil of Secrets,12/23/2015,Apple
2,Chris Evans,drama,6.1,Crimson Chase,8/10/2017,Apple
3,Meryl Streep,drama,8.2,Veil of Secrets,9/15/2019,Google
4,Jennifer Lawrence,thriller,9.0,Whispers in the Wind,10/15/2016,Disney
5,Chris Evans,action,7.1,Crimson Chase,10/10/2018,Netflix
6,Ryan Gosling,romance,8.9,Frozen Horizon,10/8/2021,Amazon
7,Emma Stone,sci-fi,7.8,The Last Stand,3/31/2019,Netflix
8,Denzel Washington,action,9.3,Eternal Ember,1/21/2019,Apple
9,Leonardo DiCaprio,sci-fi,6.3,Urban Hunt,3/31/2018,Netflix
10,Leonardo DiCaprio,drama,7.5,Shadow Realm,2/16/2022,Warner Bros
11,Natalie Portman,comedy,7.5,Crimson Chase,7/8/2022,Amazon
12,Ryan Gosling,thriller,9.0,Veil of Secrets,3/6/2023,Google
13,Scarlett Johansson,romance,8.9,Veil of Secrets,6/18/2017,Disney
14,Natalie Portman,drama,6.9,Breaking the Silence,7/16/2018,Meta
15,Tom Hardy,drama,9.0,Timeâ€™s Edge,1/19/2023,Amazon
16,Leonardo DiCaprio,sci-fi,8.0,Shadow Realm,8/8/2016,Amazon
17,Scarlett Johansson,comedy,9.0,Veil of Secrets,12/12/2017,Disney
18,Meryl Streep,romance,9.6,Deep Impact,1/22/2019,Google
19,Scarlett Johansson,thriller,9.0,Breaking the Silence,3/25/2016,Google
20,Scarlett Johansson,sci-fi,8.9,Edge of Memory,4/26/2019,Meta
21,Meryl Streep,romance,8.1,Veil of Secrets,2/17/2015,Disney
22,Ryan Gosling,sci-fi,9.0,Echoes of War,3/10/2022,Amazon
23,Ryan Gosling,action,9.0,Shadow Realm,1/14/2015,Disney
24,Tom Hardy,thriller,9.2,Bound by Honor,3/11/2016,Warner Bros
25,Tom Hardy,sci-fi,8.9,Crimson Chase,9/18/2016,Amazon
26,Scarlett Johansson,thriller,9.0,Bound by Honor,1/3/2015,Apple
27,Natalie Portman,romance,6.1,Frozen Horizon,6/13/2018,Google
28,Emma Stone,comedy,9.5,Edge of Memory,12/17/2015,Disney
29,Jennifer Lawrence,drama,9.0,Veil of Secrets,5/30/2016,Google
30,Jennifer Lawrence,thriller,9.0,Bound by Honor,10/20/2021,Meta
31,Leonardo DiCaprio,thriller,9.0,Crimson Chase,12/30/2022,Amazon
32,Chris Evans,sci-fi,8.6,Shadow Realm,10/20/2020,Meta
33,Ryan Gosling,comedy,9.0,The Silent Voice,3/28/2015,Apple
34,Denzel Washington,comedy,8.4,Whispers in the Wind,10/18/2015,Disney
35,Emma Stone,comedy,6.3,Breaking the Silence,9/15/2018,Netflix
36,Denzel Washington,comedy,7.1,Chasing Infinity,5/27/2017,Apple
37,Scarlett Johansson,sci-fi,9.0,Timeâ€™s Edge,6/18/2021,Meta
38,Leonardo DiCaprio,romance,9.2,Crimson Chase,1/22/2016,Netflix
39,Chris Evans,action,7.7,Shadow Realm,3/6/2023,Netflix
40,Ryan Gosling,drama,9.0,The Silent Voice,3/23/2016,Google
41,Leonardo DiCaprio,comedy,8.1,Nightfall,9/25/2019,Google
42,Tom Hardy,romance,9.3,Edge of Memory,12/21/2019,Warner Bros
43,Denzel Washington,drama,6.2,Veil of Secrets,3/2/2015,Netflix
44,Leonardo DiCaprio,comedy,7.6,Chasing Infinity,5/25/2017,Warner Bros
45,Chris Evans,drama,6.7,Whispers in the Wind,5/19/2019,Amazon
46,Jennifer Lawrence,action,8.9,Veil of Secrets,6/4/2022,Disney
47,Jennifer Lawrence,comedy,9.0,Crimson Chase,8/28/2015,Apple
48,Denzel Washington,drama,9.0,Breaking the Silence,7/25/2015,Apple
49,Jennifer Lawrence,thriller,9.0,Bound by Honor,10/6/2016,Netflix

Find the top actors based on their average movie rating within the genre they appear in most frequently.
â€¢  For each actor, determine their most frequent genre (i.e., the one theyâ€™ve appeared in the most).
â€¢   If there is a tie in genre count, select the genre where the actor has the highest average rating.
â€¢   If there is still a tie in both count and rating, include all tied genres for that actor.


Rank the resulting actor + genre pairs by their average rating in descending order.
â€¢  Return all actor + genre pairs that fall within the top 3 ranks (not rows), including ties.
â€¢  Do not skip ranks â€” for example, if multiple actors are tied at rank 1, the next rank is 2.

In [3]:
# sort by actors name and genre
# added a column that shows the average rating of each genre
# added another column that count the apperance of actor for each genre
top_actors_rating =  top_actors_rating[['actor_name','genre','movie_rating']].sort_values(['actor_name','genre']).groupby(['actor_name','genre'], as_index = False).agg(avg_rating=('movie_rating', 'mean'), apperance=('movie_rating', 'count'))

# show dataframe
top_actors_rating

            actor_name     genre  avg_rating  apperance
0          Chris Evans    action        7.40          2
1          Chris Evans     drama        6.40          2
2          Chris Evans    sci-fi        8.60          1
3    Denzel Washington    action        9.30          1
4    Denzel Washington    comedy        7.75          2
5    Denzel Washington     drama        7.60          2
6           Emma Stone    comedy        7.90          2
7           Emma Stone    sci-fi        7.80          1
8    Jennifer Lawrence    action        8.90          1
9    Jennifer Lawrence    comedy        9.00          1
10   Jennifer Lawrence     drama        9.00          1
11   Jennifer Lawrence  thriller        9.00          3
12   Leonardo DiCaprio    comedy        7.85          2
13   Leonardo DiCaprio     drama        7.50          1
14   Leonardo DiCaprio   romance        9.20          1
15   Leonardo DiCaprio    sci-fi        7.15          2
16   Leonardo DiCaprio  thriller        9.00          1
17        Meryl Streep     drama        8.20          1
18        Meryl Streep   romance        8.85          2
19     Natalie Portman    comedy        7.50          1
20     Natalie Portman     drama        6.90          1
21     Natalie Portman   romance        6.10          1
22        Ryan Gosling    action        9.00          1
23        Ryan Gosling    comedy        9.00          1
24        Ryan Gosling     drama        9.00          2
25        Ryan Gosling   romance        8.90          1
26        Ryan Gosling    sci-fi        8.95          2
27        Ryan Gosling  thriller        9.00          1
28  Scarlett Johansson    comedy        9.00          1
29  Scarlett Johansson   romance        8.90          1
30  Scarlett Johansson    sci-fi        8.95          2
31  Scarlett Johansson  thriller        9.00          2
32           Tom Hardy     drama        9.00          1
33           Tom Hardy   romance        9.30          1
34           Tom Hardy    sci-fi        8.90          1
35           Tom Hardy  thriller        9.20          1

Find the top actors based on their average movie rating within the genre they appear in most frequently. â€¢ For each actor, determine their most frequent genre (i.e., the one theyâ€™ve appeared in the most). â€¢ If there is a tie in genre count, select the genre where the actor has the highest average rating. â€¢ If there is still a tie in both count and rating, include all tied genres for that actor.

In [4]:
# add column that show maximum apperance by each actor
top_actors_rating['max_apperance'] = top_actors_rating.groupby(['actor_name'])['apperance'].transform('max')

# show table
top_actors_rating

            actor_name     genre  avg_rating  apperance  max_apperance
0          Chris Evans    action        7.40          2              2
1          Chris Evans     drama        6.40          2              2
2          Chris Evans    sci-fi        8.60          1              2
3    Denzel Washington    action        9.30          1              2
4    Denzel Washington    comedy        7.75          2              2
5    Denzel Washington     drama        7.60          2              2
6           Emma Stone    comedy        7.90          2              2
7           Emma Stone    sci-fi        7.80          1              2
8    Jennifer Lawrence    action        8.90          1              3
9    Jennifer Lawrence    comedy        9.00          1              3
10   Jennifer Lawrence     drama        9.00          1              3
11   Jennifer Lawrence  thriller        9.00          3              3
12   Leonardo DiCaprio    comedy        7.85          2              2
13   Leonardo DiCaprio     drama        7.50          1              2
14   Leonardo DiCaprio   romance        9.20          1              2
15   Leonardo DiCaprio    sci-fi        7.15          2              2
16   Leonardo DiCaprio  thriller        9.00          1              2
17        Meryl Streep     drama        8.20          1              2
18        Meryl Streep   romance        8.85          2              2
19     Natalie Portman    comedy        7.50          1              1
20     Natalie Portman     drama        6.90          1              1
21     Natalie Portman   romance        6.10          1              1
22        Ryan Gosling    action        9.00          1              2
23        Ryan Gosling    comedy        9.00          1              2
24        Ryan Gosling     drama        9.00          2              2
25        Ryan Gosling   romance        8.90          1              2
26        Ryan Gosling    sci-fi        8.95          2              2
27        Ryan Gosling  thriller        9.00          1              2
28  Scarlett Johansson    comedy        9.00          1              2
29  Scarlett Johansson   romance        8.90          1              2
30  Scarlett Johansson    sci-fi        8.95          2              2
31  Scarlett Johansson  thriller        9.00          2              2
32           Tom Hardy     drama        9.00          1              1
33           Tom Hardy   romance        9.30          1              1
34           Tom Hardy    sci-fi        8.90          1              1
35           Tom Hardy  thriller        9.20          1              1

In [5]:
# Find the top actors based on their average movie rating within the genre they appear in most frequently

# This is done by returing rows where apperance and max_apperance matches
top_actors_rating = top_actors_rating[['actor_name', 'avg_rating', 'genre', 'apperance']][top_actors_rating['apperance' ] == top_actors_rating['max_apperance']]

#show
top_actors_rating

            actor_name  avg_rating     genre  apperance
0          Chris Evans        7.40    action          2
1          Chris Evans        6.40     drama          2
4    Denzel Washington        7.75    comedy          2
5    Denzel Washington        7.60     drama          2
6           Emma Stone        7.90    comedy          2
11   Jennifer Lawrence        9.00  thriller          3
12   Leonardo DiCaprio        7.85    comedy          2
15   Leonardo DiCaprio        7.15    sci-fi          2
18        Meryl Streep        8.85   romance          2
19     Natalie Portman        7.50    comedy          1
20     Natalie Portman        6.90     drama          1
21     Natalie Portman        6.10   romance          1
24        Ryan Gosling        9.00     drama          2
26        Ryan Gosling        8.95    sci-fi          2
30  Scarlett Johansson        8.95    sci-fi          2
31  Scarlett Johansson        9.00  thriller          2
32           Tom Hardy        9.00     drama          1
33           Tom Hardy        9.30   romance          1
34           Tom Hardy        8.90    sci-fi          1
35           Tom Hardy        9.20  thriller          1

In [6]:
#If there is a tie in genre count, select the genre where the actor has the highest average rating
#If there is still a tie in both count and rating, include all tied genres for that actor.

# Added a column that shows max avg_rating of each actor
top_actors_rating['max_avg_rating'] = top_actors_rating.groupby(['actor_name'])['avg_rating'].transform('max')

#show
top_actors_rating

            actor_name  avg_rating     genre  apperance  max_avg_rating
0          Chris Evans        7.40    action          2            7.40
1          Chris Evans        6.40     drama          2            7.40
4    Denzel Washington        7.75    comedy          2            7.75
5    Denzel Washington        7.60     drama          2            7.75
6           Emma Stone        7.90    comedy          2            7.90
11   Jennifer Lawrence        9.00  thriller          3            9.00
12   Leonardo DiCaprio        7.85    comedy          2            7.85
15   Leonardo DiCaprio        7.15    sci-fi          2            7.85
18        Meryl Streep        8.85   romance          2            8.85
19     Natalie Portman        7.50    comedy          1            7.50
20     Natalie Portman        6.90     drama          1            7.50
21     Natalie Portman        6.10   romance          1            7.50
24        Ryan Gosling        9.00     drama          2            9.00
26        Ryan Gosling        8.95    sci-fi          2            9.00
30  Scarlett Johansson        8.95    sci-fi          2            9.00
31  Scarlett Johansson        9.00  thriller          2            9.00
32           Tom Hardy        9.00     drama          1            9.30
33           Tom Hardy        9.30   romance          1            9.30
34           Tom Hardy        8.90    sci-fi          1            9.30
35           Tom Hardy        9.20  thriller          1            9.30

In [7]:
#If there is a tie in genre count, select the genre where the actor has the highest average rating
#If there is still a tie in both count and rating, include all tied genres for that actor.

# This is done by returing rows where avg_rating and max_avg_rating matches
top_actors_rating = top_actors_rating[['actor_name', 'avg_rating', 'genre', 'apperance']][top_actors_rating['avg_rating' ] == top_actors_rating['max_avg_rating']]

# show
top_actors_rating

            actor_name  avg_rating     genre  apperance
0          Chris Evans        7.40    action          2
4    Denzel Washington        7.75    comedy          2
6           Emma Stone        7.90    comedy          2
11   Jennifer Lawrence        9.00  thriller          3
12   Leonardo DiCaprio        7.85    comedy          2
18        Meryl Streep        8.85   romance          2
19     Natalie Portman        7.50    comedy          1
24        Ryan Gosling        9.00     drama          2
31  Scarlett Johansson        9.00  thriller          2
33           Tom Hardy        9.30   romance          1

Rank the resulting actor + genre pairs by their average rating in descending order. â€¢ Return all actor + genre pairs that fall within the top 3 ranks (not rows), including ties. â€¢ Do not skip ranks â€” for example, if multiple actors are tied at rank 1, the next rank is 2.

In [8]:
#Rank the resulting actor + genre pairs by their average rating in descending order.
top_actors_rating['rank'] = top_actors_rating['avg_rating'].rank(method = 'dense', ascending = False)

top_actors_rating

            actor_name  avg_rating     genre  apperance  rank
0          Chris Evans        7.40    action          2   8.0
4    Denzel Washington        7.75    comedy          2   6.0
6           Emma Stone        7.90    comedy          2   4.0
11   Jennifer Lawrence        9.00  thriller          3   2.0
12   Leonardo DiCaprio        7.85    comedy          2   5.0
18        Meryl Streep        8.85   romance          2   3.0
19     Natalie Portman        7.50    comedy          1   7.0
24        Ryan Gosling        9.00     drama          2   2.0
31  Scarlett Johansson        9.00  thriller          2   2.0
33           Tom Hardy        9.30   romance          1   1.0

In [9]:
#Return all actor + genre pairs that fall within the top 3 ranks (not rows), including ties.
top_actors_rating[['actor_name', 'genre','avg_rating']][top_actors_rating['rank'] <= 3]

            actor_name     genre  avg_rating
11   Jennifer Lawrence  thriller        9.00
18        Meryl Streep   romance        8.85
24        Ryan Gosling     drama        9.00
31  Scarlett Johansson  thriller        9.00
33           Tom Hardy   romance        9.30